from Sistema.Sistema_Ponto_Turistico import Sistema
sistema = Sistema()
"""
print(sistema.adicionar_ponto("Ponto 1", designacao="Designação 1", categorias=""))
print(sistema.adicionar_ponto("Ponto 2", designacao="Designação 1", categorias="natureza"))
print(sistema.obter_ponto("Ponto 2"))
print(sistema.remover_ponto("Ponto 2"))
print(sistema.obter_ponto("Ponto 2"))
print(sistema.adicionar_ponto("Ponto 1", designacao="B", categorias="natureza"))
print(sistema.adicionar_ponto("Ponto 2", designacao="A", categorias="natureza"))
print(sistema.adicionar_ponto("Ponto 3", designacao="C", categorias="natureza"))

print(sistema.listar_pontos())
# print(sistema.pesquisar_por_categoria("natureza"))
print(sistema.assinalar_visita("Ponto 3"))
print(sistema.assinalar_visita("Ponto 3"))
print(sistema.assinalar_visita("Ponto 2"))
print(sistema.avaliar_experiencia("Ponto 3", 20))
print(sistema.avaliar_experiencia("Ponto 3", 10))
print(sistema.avaliar_experiencia("Ponto 3", 10))
print(sistema.obter_ponto("Ponto 3"))
print(sistema.consultar_estatisticas())
print(sistema.sugerir_pontos_interesse([10, 10]))
print(sistema.atualizar_dados("Ponto_turistico_data.json"))
"""
print(sistema.carregar_dados("Ponto_turistico_data.json"))
print(sistema.obter_ponto("Ponto 3"))
print(sistema.avaliar_experiencia("teste", 20))
print(sistema.avaliar_experiencia("teste", 10))
print(sistema.obter_ponto("teste"))
print(sistema.assinalar_visita("teste"))
print(sistema.obter_ponto("teste"))
print(sistema.atualizar_dados("Ponto_turistico_data.json"))